### ISSUE TITLE
lazy.min.js contains es6 syntax

### ISSUE THREAD

**Issue by alexpidhornyi** [overlookmotel/react-lazy-ssr#23]
Hi there,
My project won't run on IE11 because of this line:
`var y=(e,t)=>v.call(e,t);`
Which is located in node_modules/react-lazy-ssr/dist/lazy.min.js
I presume it comes from this line:
`var hasOwnProp_1 = (object, property) => hasOwnProp.call(object, property);`

I would appreciate if you can address this issue at some point.

**Comment by overlookmotel** [comment]
Sorry about that. Thanks for spotting it.

Cause was the [has-own-prop](https://www.npmjs.com/package/has-own-prop) dependency. I'd assumed it was built as ES5, but no!

Anyway, fixed in v0.2.3, just released.
